esphome:
  name: wireless-speaker
  friendly_name: Wireless Speaker
  # Set volume to 15% on boot
  on_boot:
    priority: -100 # Run after initialization
    then:
      - media_player.volume_set: 
          id: wireless_speaker
          volume: 0.15

esp32:
  board: esp32dev

# Enable logging. Default is DEBUG
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret ha_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

# Enable wireless connectivity to the network
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # The local network is not .local
  domain: ".home.arpa"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wireless-Speaker"
    password: !secret wifi_ap_password

captive_portal:

# Enable the ESP32 local webserver
web_server:
  port: 80

i2s_audio: 
  id: dac_connect
  i2s_lrclk_pin: GPIO27  # Pin for Left/Right Clock 
  i2s_bclk_pin: GPIO25  # Pin for Bit Clock 

media_player: 
  - platform: i2s_audio  # Defines a media player using I2S audio  
    dac_type: external  # Specifies that an external DAC is used 
    i2s_dout_pin: GPIO26  # Pin for Data Out 
    i2s_audio_id: dac_connect
    mode: stereo
    id: wireless_speaker # The ID of the media player
    name: None  # Uses the friendly name of the device.
   
